version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8051:8051"
    depends_on:
      - hasura
  hasura:
    image: hasura/graphql-engine:v2.4.0 # Replace with the latest version
    ports:
      - "8070:8070"
    environment:
      - HASURA_GRAPHQL_SERVER_PORT=8050
      - HASURA_GRAPHQL_METADATA_DATABASE_URL=postgres://postgres:postgres@ehr-finance-api-postgres-1:5432/finance
      - PG_DATABASE_URL=postgres://postgres:postgres@ehr-finance-api-postgres-1:5432/finance
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:postgres@ehr-finance-api-postgres-1:5432/finance # Update the PostgreSQL connection URL
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup, http-log, webhook-log, websocket-log, query-log
    volumes:
      - ./migrations:/hasura-migrations
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres # Replace with your desired PostgreSQL username
      - POSTGRES_PASSWORD=postgres # Replace with your desired PostgreSQL password
      - POSTGRES_DB=finance # Replace with your desired PostgreSQL database name
    volumes:
      - ./pg_data:/var/lib/postgresql/data
